### ISSUE TITLE
1.8 Rendering for Greek Fire

### ISSUE THREAD

**Issue by josiahseaman** [Runix-Minecraft/Runix#74]
http://bdcraft.net/cubik

**Comment by LordIllyohs** [comment]
As usual I was wrong about rendering forge wise alot of things changed between 1.8 and now rendering wise but looking into more it looks like Cubik  _might_  not be capable of doing what we need. But the old way of rendering blocks is gone ISimpleBlockRenderer no longer exsits

**Comment by josiahseaman** [comment]
So are you saying all my precious render coordinates for the Tesselator patterns on Greek Fire and Hoar Frost have been rendered obsolete?

**Comment by LordIllyohs** [comment]
Yes... Im not sure about how to port them quite yet haven't played looked through 1.8 all much might look through it later this week

**Comment by josiahseaman** [comment]
https://github.com/Runix-Minecraft/Runix/issues/81?_pjax=%23js-repo-pjax-container#issuecomment-341374085
