### ISSUE TITLE
FTP should use Ctri's animation style

### ISSUE THREAD

**Issue by josiahseaman** [Runix-Minecraft/Runix#79]
There are issues with moving overlapping sphere volumes that are solved by Ctri's slick wall of glass animation.  With our moveSensitive storage, I don't think the glass is sensitive.  However, I do like the layer by layer animation.

![image](https://user-images.githubusercontent.com/2256148/30227667-59de78f4-94d2-11e7-892a-ca161e774dae.png)

**Comment by BinaryBandit** [comment]
Just got a random email from GitHub about an issue tracker, kinda surprised to see it was this. Just out of curiosity, do you have the rest of your team or is it just you? Are you just fixing bugs and dropping it again? If you are continuing to develop, are you continuing to develop on 1.7 or are you moving forward?

**Comment by josiahseaman** [comment]
Lol, I wonder how many people are in your same position?  I'm going to revive Runix and update it for 1.12.  But I'm doing it for my own enjoyment.  I'm going to make zero effort to take feedback or balance the game.  I will take proper pull requests though.
